### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by InfoHunter** [01org/QAT_Engine#10]
Hi there,

Actually there are 2 issues I found in the QAT1.6 driver and the nginx-1.10.0 async patch, I don't know where else to post the issues,  so I have to post them here in QAT Engine project. If this is not a correct place, pls help me moving them into the correct one.

1) QAT1.6 driver built with OpenSSL 1.1.0 or later will not be loaded due to a 'undefined reference to SHA_Init' problem. After I dig into OpenSSL 1.1.0, I have not found 'SHA_Init', the API is not there anymore. The QAT1.6 driver I used is downloaded from 01org website, the latest one.

2) For nginx-patch of async use of QAT, the problem is the patch does not support the following style of nginx configuration file: `listen 443 ssl;`, it only supports the `ssl on;` directive. And no document mentions this situation, and this really caused me lots of time to resolve the problem.

**Comment by agrandi** [comment]
Hi @InfoHunter 

Thanks a lot for reporting these issues.
I have created two separate issues to track them separately: #12  - #13
