### ISSUE TITLE
undefined symbol: SHA_Init in QAT 1.6 driver

### ISSUE THREAD

**Issue by agrandi** [01org/QAT_Engine#12]
Originally reported here #10 by @InfoHunter 

QAT1.6 driver built with OpenSSL 1.1.0 or later will not be loaded due to a 'undefined reference to SHA_Init' problem. After I dig into OpenSSL 1.1.0, I have not found 'SHA_Init', the API is not there anymore. 

The QAT1.6 driver I used is downloaded from 01org website, the latest one.

**Comment by agrandi** [comment]
@InfoHunter, could you please provide more details about when you see the error?
It would be very useful to have the sequence of steps that you are doing so we can try to reproduce the error locally.

**Comment by InfoHunter** [comment]
Hi @agrandi , check the following steps:

1. Build QAT1.6 driver as what the doc says (doc ref: 330750-005): `./installer.sh` and then choose 1, 3 to build QAT1.6 driver
2. Build OpenSSL 1.1.0 (exact 1.1.0, not later version) and QAT_Engine 0.5.7 (git checks out from this project) as what README.md file tells (yeah, just the README file sit in this repo): `./configure --with-qat_dir=/path/to/qat_driver/QAT1.6 --with-qat_install_dir=/path/to/qat_driver/QAT1.6/build --with-openssl_dir=/path/to/openssl-1.1.0 --with-openssl_install_dir=/path/to/installed/openssl && make depend && make && make install`
3. run `/path/to/installed/openssl/bin/openssl engine -t -c -vvv qat` fails, the output is as following:

`139692719335168:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:111:filename(/path/to/ssl/lib/engines-1.1/qat.so): /root/httpsproject/intel/qat_driver/QAT1.6/build/libicp_qa_al_s.so: undefined symbol: SHA_Init
139692719335168:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:159:
139692719335168:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
139692719335168:error:260BC066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:141:section=qat_section, name=dynamic_path, value=/usr/local/intel/ssl/lib/engines-1.1/qat.so
139692719335168:error:0E07606D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:173:module=engines, value=engine_section, retcode=-1
139692719335168:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:111:filename(/path/to/ssl/lib/engines-1.1/qat.so): /root/httpsproject/intel/qat_driver/QAT1.6/build/libicp_qa_al_s.so: undefined symbol: SHA_Init
139692719335168:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:159:
139692719335168:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
139692719335168:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=qat`

So it's "undefined symbol: SHA_Init"

**Comment by InfoHunter** [comment]
oops, the lines do not look beautiful, some new-line characters are missing...

**Comment by InfoHunter** [comment]
the piece of code locates in utilities/osal/src/linux/user_space/OsalCryptoInterface.c:

```
77 OSAL_STATUS
 78 osalHashSHA1(UINT8 *in, UINT8 *out)
 79 {
 80     SHA_CTX ctx;
 81     if(!SHA_Init(&ctx))
 82     {
 83         return OSAL_FAIL;
 84     }
 85     SHA1_Transform(&ctx, in);
 86     memcpy(out, &ctx, SHA_DIGEST_LENGTH);
 87     return OSAL_SUCCESS;
 88 }
```

line 81. Is it not a typo ? After I change SHA_Init to SHA1_Init, everything goes smoothly

**Comment by InfoHunter** [comment]
The QAT1.6 driver I used is retrieved from: https://01.org/sites/default/files/page/qatmux.l.2.6.0-60.tgz

**Comment by agrandi** [comment]
The APIs of OpenSSL 1.1.0 are **not** backward compatible with OpenSSL 1.0.1

The QAT driver has a dependency on the old version of OpenSSL, which should be installed on your system.
For this reason, you must make sure that the library `libicp_qa_al_s.so` is linked to the correct version of `libcrypto.so`.

For example, on my system:

```bash
$ ldd libicp_qa_al_s.so
        linux-vdso.so.1 =>  (0x00007fff5e1e2000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f696a02a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f6969e25000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6969c09000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f6969870000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f6969658000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f696a6a3000)
```

Linking the driver to the newer version of OpenSSL could cause unexpected behaviors or errors.

**Comment by InfoHunter** [comment]
@agrandi why does my libicp_qa_al_s.so link to libcrypto.so.1.1 instead of libcrypto.so.10 ?

```
[root@localhost build]# ldd libicp_qa_al_s.so
	linux-vdso.so.1 =>  (0x00007fff6cf24000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f32fd2f4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f32fd0f0000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f32fced2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f32fd934000)
	libcrypto.so.1.1 => not found
```

I do have a libcrypto.so.10 in /usr/lib64.

**Comment by agrandi** [comment]
@InfoHunter , we will follow up to your request as soon as the team is back from the holidays.

Thanks for your patience 👍

**Comment by InfoHunter** [comment]
Sure, no problem

**Comment by jdschuet** [comment]
@InfoHunter  - I'm not able to replicate the issue reported (SHA_Init symbol being undefined)
Steps performed:
- Download QATmux package from 01.org (https://01.org/sites/default/files/page/qatmux.l.2.6.0-60.tgz)
- Install (installation script, option 3)
- Install OpenSSL and QAT engine using instructions in README.md file.  I used the source and install directories from the README (/QAT, /openssl. /openssl/engines/). 
- Export LD_LIBRARY_PATH=/usr/local/ssl/lib

With these steps the installation is successful.  If you'd like we could schedule a debug session to walk through these steps.

Thanks,
Joel

**Comment by InfoHunter** [comment]
@jdschuet 

Could you show me which libcrypto.so does lib libicp_qa_al_s.so link to? I don't think if your libicp_qa_al_s.so lilnks to the libcrypto.so built from OpenSSL 1.1.0 you can still use the openssl engine app to test QAT engine.

**Comment by jdschuet** [comment]
@InfoHunter 
# ldd libicp_qa_al_s.so
...
libcrypto.so.10 => /lib64/libcrypto.so.10
...

**Comment by InfoHunter** [comment]
@jdschuet 

So this one is the libcrypto delivered by the OS. I may know the reason in my case: libicp_qa_al_s.so links to the newly built OpenSSL 1.1.0's libcrypto.

One more thing to be confirmed: can the QAT driver only be linked with OpenSSL 1.0.1, just as @agrandi mentioned days ago ?

**Comment by jdschuet** [comment]
@InfoHunter 
I believe @agrandi is correct.  Here is link to OpenSSL 1.1.0 manpage for SHA functions:
         https://www.openssl.org/docs/man1.1.0/crypto/SHA256_Init.html
SHA_Init() is not defined.  

Are you able to update your compilation of QAT driver to utilize OpenSSL 1.0.1?

**Comment by wenxin1234114** [comment]
@agrandi @InfoHunter  QAT_Engine is not compatible with Openssl 1.1.0e ,which supported in nginx-1.10.3-async.l.0.3.0-002.tar.gz

**Comment by InfoHunter** [comment]
It's definitely compatible with OpenSSL 1.1.0e. If I recall correctly, you should build openssl dynamically with nginx. Link nginx to libssl.so and libcrypto.so, static linked might not work.

**Comment by wenxin1234114** [comment]
@InfoHunter But I can not run :openssl engine -t -c -vvvv qat  ,detail in this thread :https://github.com/01org/QAT_Engine/issues/25#issuecomment-306073401

**Comment by InfoHunter** [comment]
Ahhh, I remember something. It's a little tricky, 'libicp_qa_al_s.so' should be linked to an OpenSSL 1.0.1 and the nginx binary should be linked to OpenSSL 1.1.0...

**Comment by wenxin1234114** [comment]
@InfoHunter I am confused . ldd QAT/QAT1.6/build/libicp_qa_al_s.so ,	linux-vdso.so.1 =>  (0x00007ffe439f9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f003a2da000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f003a0d5000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0039eb9000)
	**libcrypto.so.1.1 => /opt/xyz/ssl/lib/libcrypto.so.1.1** (0x00007f0039a36000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f003a949000)
As you said ,this libcrypto.so.1.1 link to openssl 1.1.0e .But how to fix this ?

**Comment by InfoHunter** [comment]
Maybe you need to use the ld option ‘-rpath’ to tell the QAT1.6 driver to link to which openssl in your system at ‘runtime'. You might change something in QAT1.6 driver’s configuration script or Makefile, I don’t know.

For ‘-rpath’, dig it in Google.

**Comment by stevelinsell** [comment]
Hi @wenxin1234114, @InfoHunter is correct there is something in your environment that is causing the QAT1.6 driver to your build of OpenSSL 1.1.0 rather than the system OpenSSL.

Can you check the following for me:
What version of OpenSSL do you have in /lib64?
Whether you have/or had the LD_LIBRARY_PATH environment variable set to point to where you have built OpenSSL 1.1.0 at the time that you build the QAT 1.6 driver (this is usually the cause).

Please can you try rebuilding the QAT1.6 driver without LD_LIBRARY_PATH being set and without any other environment variables set that point to the OpenSSL 1.1.0 install and then do an ldd on the resulting libicp_qa_al_s.so library.

Let me know if that results in the QAT1.6 driver pointing to the correct OpenSSL residing in /lib64.

Steve.

**Comment by wenxin1234114** [comment]
@stevelinsell I have solved this issue with help of @InfoHunter .Thank you very much.

**Comment by zhangkyou** [comment]
my libicp_qa_al_s.so was linked to the older libcrypto.so.10,like this:
ldd libicp_qa_al_s.so
linux-vdso.so.1 =>  (0x00007ffe8b7db000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f87a7b00000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f87a78fb000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f87a76df000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f87a72f5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f87a8170000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f87a70de000)
but I am want it link to the libcrypto.so.1.1 built by openssl-1.1.0e
I try to set LD_LIBRARY_PATH and add openssl-1.1.0e lib dir to ld.so.conf file,but it didn't work
please help me.

**Comment by stevelinsell** [comment]
Hi @zhangkyou,

Your libicp_qa_al_s.so library *needs* to link against an older OpenSSL.
libicp_qa_al_s.so uses symbols that are only present in the older OpenSSL library and will give you errors if you try and link against OpenSSL 1.1.0e. The QAT Driver uses very little functionality from OpenSSL so it won't matter that you are linking in an older version down at that level. You can and will still need to link in OpenSSL 1.1.0e (or OpenSSL 1.1.0f now) at your top level application level where you are wanting to use the QAT Engine.

Hope that helps,

Steve.

**Comment by zhangkyou** [comment]
@stevelinsell 
Thanks for your reply.But there are still some problems.
If my libicp_qa_al_s.so library link against to an older OpenSSL like this:

ldd libicp_qa_al_s.so
linux-vdso.so.1 => (0x00007ffe8b7db000)
libc.so.6 => /lib64/libc.so.6 (0x00007f87a7b00000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f87a78fb000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f87a76df000)
libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f87a72f5000)
/lib64/ld-linux-x86-64.so.2 (0x00007f87a8170000)
libz.so.1 => /lib64/libz.so.1 (0x00007f87a70de000)

then when I start my openresty(nginx) give me an errror like this:
nginx: [warn] ENGINE_by_id("qat") failed (SSL: error:25066067:DSO support routines:dlfcn_load:could not load the shared library:filename(/home/s/qat/ssl/lib/engines-1.1/qat.so): /home/s/qat/ssl/lib/engines-1.1/qat.so: undefined symbol: RSA_meth_get_pub_dec error:25070067:DSO support routines:DSO_load:could not load the shared library error:260B6084:engine routines:dynamic_load:dso not found error:2606A074:engine routines:ENGINE_by_id:no such engine:id=qat)

the nginx.conf with this config: "ssl_engine qat;"

**Comment by stevelinsell** [comment]
@zhangkyou,
By the sound of your issue both libicp_qa_al_s.so and the QAT Engine (qat.so) are linking against the older OpenSSL. When you configure the QAT Engine build you need to ensure that --with-openssl_install_dir is specified and is pointing to an OpenSSL 1.1.0 install. Also ensure that you have not set your LD_LIBRARY_PATH environment variable to point to a folder containing an older OpenSSL install or it might overide the path you have set.
If you do:
ldd qat.so 
you should get a list of the OpenSSL version that is trying to be linked into qat.so.
If you still have problems please post that output here.

Kind Regards,

Steve.

**Comment by zhangkyou** [comment]
@stevelinsell
this is the ldd qat.so output:
        linux-vdso.so.1 =>  (0x00007fffb2fde000)
        libicp_qa_al_s.so => /home/s/qat/QAT/QAT1.6/build/libicp_qa_al_s.so (0x00007f5c97c9d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f5c978d1000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f5c976cd000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5c974b1000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f5c970c6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5c98165000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f5c96eb0000)

my openssl-1.1.0e installed to /home/s/qat/ssl,and specify the --with-openssl_install_dir=/home/s/qat/ssl.And in order to let the qat.so link against the newer openssl,I set LD_LIBRARY_PATH = :/home/s/qat/ssl/lib(i.e. this dir includes the libcrypto.so.1.1).
But after QAT Engine build,the qat.so still link against the older openssl.
I promise what I do was according to the manual in https://github.com/01org/QAT_Engine#clone-the-intel-quickassist-technology-openssl-engine.
But the problem is still like what I said before.
If you need any info or ENVIRONMENT about my PC,please tell me.

**Comment by wenxin1234114** [comment]
@zhangkyou I complied openssl  with rpath:
./config --prefix=/opt/tuniu/ssl -Wl,-rpath=/opt/tuniu/ssl/lib
als you can add this:
echo "/usr/local/lib64" > /etc/ld.so.conf.d/openssl.conf
After that ,new version openssl will find the right qat.so dependency file

**Comment by zhangkyou** [comment]
@wenxin1234114 thanks for reply.
I tried your method to install the openssl,after that I installed the QAT driver,then:

ll /usr/local/lib64
total 0
lrwxrwxrwx 1 root root 36 Jun 15 20:48 libcrypto.so.1.1 -> /home/s/qat/ssl/lib/libcrypto.so.1.1
lrwxrwxrwx 1 root root 33 Jun 15 20:47 libssl.so.1.1 -> /home/s/qat/ssl/lib/libssl.so.1.1

cat /etc/ld.so.conf.d/openssl.conf
/usr/local/lib64

ldd /home/s/qat/QAT/QAT1.6/build/libicp_qa_al_s.so 
        linux-vdso.so.1 =>  (0x00007fffc037b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9748ce9000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9748ae4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f97488c8000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f97484de000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9749359000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f97482c7000)

so...it didn't work...
The QAT driver installer.sh seemingly always to find libcrypto in /lib64/
ll /lib64/libcrypto*
lrwxrwxrwx 1 root root      19 Dec 23 16:08 /lib64/libcrypto.so -> libcrypto.so.1.0.1e
lrwxrwxrwx 1 root root      19 Dec 23 16:08 /lib64/libcrypto.so.10 -> libcrypto.so.1.0.1e
-rwxr-xr-x 1 root root 2025472 Nov  6  2016 /lib64/libcrypto.so.1.0.1e

**Comment by Xuexiang825** [comment]
@zhangkyou have you fixed this issue . you can email me ,chat with Wechat.

**Comment by zhangkyou** [comment]
@Xuexiang825 
what's your email address or wechat username?

**Comment by Xuexiang825** [comment]
@zhangkyou email :xuexiang825#126.com
