### ISSUE TITLE
question about QAT, Openssl 1.1.0e+Nginx 1.10.3

### ISSUE THREAD

**Issue by xiaoliangaa** [01org/QAT_Engine#20]
Dell R630 128GB E5-2660 v3 2.60GHz
Centos 7.2  kernel 3.10.0-327.36.3.el7.x86_64
Openssl1.1.0e + nginx1.10.3
dh895xcc_qa_dev0.conf,  opensll.cnf, nginx.conf, those three conf files were used.

1, Openssl testing error, when I run openssl engine

/openssl engine
(rdrand) Intel RDRAND engine
(dynamic) Dynamic engine loading support
139663619606336:error:0E079065:configuration file routines:def_load_bio:missing equal sign:crypto/conf/conf_def.c:294:line 1

2, After I setup Nginx following readme, it doesn't work. 

 Statistics for Qat Instance 0                    |
+--------------------------------------------------+
| Firmware Requests[AE 0]:                       0 |
| Firmware Responses[AE 0]:                      0 

Could anyone kindly give me some advice. 
Many thanks.

**Comment by stevelinsell** [comment]
Hi,

This looks like an error in the openssl.cnf as OpenSSL appears to be flagging up an error parsing a config file.
Could you post the contents of the openssl.cnf, just the lines that are additional to a standard openssl.cnf that comes with an OpenSSL distribution. We'll then take a look and see if we can spot which line is causing the issue.

Kind Regards,

Steve.

**Comment by xiaoliangaa** [comment]
sorry,I'm busy but forget it;Becsuse openssl.cnf contains illegal character but Cannot see
