### ISSUE TITLE
qat_engine_init()] No crypto instances found

### ISSUE THREAD

**Issue by guobinchn** [01org/QAT_Engine#22]
error log:   [error.zip](https://github.com/01org/QAT_Engine/files/982889/error.zip)

I setup dh8955 on centos 6.8(64bit) at HP DL360 Gen9,
software env:  nginx-1.10.3+openssl-1.1.0e+QAT_Engine-0.5.22

the nginx error follow ,and happend it every day,
Very interesting is that every day around five o'clock, about 10 minutes after the normal.

so ,can anyone help me ,thanks.

[WARNING][e_qat.c:1009:qat_engine_init()] No crypto instances found
[WARNING][e_qat.c:1009:qat_engine_init()] No crypto instances found
[WARNING][e_qat.c:1009:qat_engine_init()] No crypto instances found
[WARNING][e_qat.c:1009:qat_engine_init()] No crypto instances found
[WARNING][e_qat.c:1009:qat_engine_init()] No crypto instances found
[WARNING][e_qat.c:1009:qat_engine_init()] No crypto instances found
[WARNING][e_qat.c:299:engine_init_child_at_fork_handler()] Failure in qat_engine_init function
[WARNING][e_qat.c:299:engine_init_child_at_fork_handler()] Failure in qat_engine_init function
[WARNING][e_qat.c:299:engine_init_child_at_fork_handler()] Failure in qat_engine_init function
[WARNING][e_qat.c:299:engine_init_child_at_fork_handler()] Failure in qat_engine_init function
[WARNING][e_qat.c:299:engine_init_child_at_fork_handler()] Failure in qat_engine_init function
[WARNING][e_qat.c:299:engine_init_child_at_fork_handler()] Failure in qat_engine_init function
[WARNING][e_qat.c:299:engine_init_child_at_fork_handler()] Failure in qat_engine_init function
[WARNING][e_qat.c:256:get_next_inst()] Failure in qat_engine_init function
[WARNING][qat_rsa.c:433:qat_rsa_decrypt()] Failed to get an instance
[WARNING][qat_rsa.c:1047:qat_rsa_priv_dec()] Failure in qat_rsa_decrypt
[WARNING][e_qat.c:1009:qat_engine_init()] No crypto instances found
[WARNING][e_qat.c:256:get_next_inst()] Failure in qat_engine_init function
[WARNING][qat_rsa.c:433:qat_rsa_decrypt()] Failed to get an instance
[WARNING][qat_rsa.c:1047:qat_rsa_priv_dec()] Failure in qat_rsa_decrypt

**Comment by stevelinsell** [comment]
Hi @guobinchn, it is a very interesting that this seems to happen at the same sort of time everyday. 
Could there be any kind of maintenance/backup happening on your server at that time?

In the past I have seen maintenance/backup cycles that use something like:

` kill -HUP $( cat /path/to/nginx.pid )`

to restart the nginx servers.
The problem with using the HUP signal is that it will start new nginx child processes and the the existing child processes will continue to run until they have finished dealing with any outstanding requests.
This means at any one time you could have twice as many nginx child processes running than you expect.
This has implications to the number of processes you specify in the Intel Quickassist Driver configuration file. For example if you specify NumOfProcesses = 32 in the configuration file and then run nginx with 32 worker processes then you need to be aware that if you send a HUP signal to nginx you could have 64 worker processes trying to use the acceleration device. If that happens the 32 new worker processes will get errors like you see above when they are unable to get any crypto instances.
If you are expecting to send the HUP signal to nginx you should specify more processes in the Intel Quickassist Driver configuration file to take account of this.

This is only a guess at one possible cause for the errors you are seeing, but please have a look and see if that could be what is happening.

**Comment by guobinchn** [comment]
thanks, it solved
