### ISSUE TITLE
nginx can not start with not-root user

### ISSUE THREAD

**Issue by wenxin1234114** [01org/QAT_Engine#24]
nginx can not start with root user ,error log shows:
open qat_contig_mem: Permission denied
open qat_contig_mem: Permission denied
open qat_contig_mem: Permission denied
open qat_contig_mem: Permission denied
open qat_contig_mem: Permission denied
open qat_contig_mem: Permission denied
open qat_contig_mem: Permission denied
open qat_contig_mem: Permission denied
how fix this ?

**Comment by InfoHunter** [comment]
There is a document describing how to use non-root user with QAT driver. 

Document number is 330751, chapter 4.16 - Running Applications as Non-Root User

**Comment by wenxin1234114** [comment]
where can I find the document number 330751?

**Comment by stevelinsell** [comment]
The document is on the 01.org website if you search for QuickAssist.
The document is called:
Intel® Communications Chipset 8925 to 8955 Series Software - Programmer's Guide
Here is a direct link but it will take you to a specific version that might go out of date over time:
https://01.org/sites/default/files/page/330751-006_clc_pg.pdf

Note: this document only deals with the changes necessary to run the Intel QuickAssist Driver as a non-root user, not the engine and qat_contig_mem parts but you should follow the same principle.

**Comment by wenxin1234114** [comment]
thank you very much

**Comment by luna0507** [comment]
I have the same problem when I start the nginx as a root user.@stevelinsell, could you please give me some suggestions?

**Comment by luna0507** [comment]
I have the same problem when I start the nginx as a root user.@stevelinsell could you please give me some suggestions?

**Comment by stevelinsell** [comment]
Hi @luna0507,

Can you confirm, are you having an issue when running as root user or when starting as a non-root user?
Just checking it wasn't a typo as it seems strange to get a permissions issue if you're running as root.

Kind Regards,

Steve.
