### ISSUE TITLE
openssl engine -t -c -vvvv qat can not run 

### ISSUE THREAD

**Issue by wenxin1234114** [01org/QAT_Engine#25]
version:
kernel:3.10.0-327.el7.x86_64
openssl-1.1.0e
qatmux.l.2.6.0-60.tgz

**openssl engine -t -c -vvvv qat**  error log following:
> 
140290782750528:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/opt/xyz/ssl/lib/engines-1.1/qat.so): /opt/xyz/QAT/QAT1.6/build/libicp_qa_al_s.so: undefined symbol: SHA_Init
140290782750528:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
140290782750528:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
140290782750528:error:260BC066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:141:section=qat_section, name=dynamic_path, value=/opt/xyz/ssl/lib/engines-1.1/qat.so
140290782750528:error:0E07606D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:173:module=engines, value=engine_section, retcode=-1
140290782750528:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:113:filename(/opt/xyz/ssl/lib/engines-1.1/qat.so): /opt/xyz/QAT/QAT1.6/build/libicp_qa_al_s.so: undefined symbol: SHA_Init
140290782750528:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
140290782750528:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
140290782750528:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=q

**/etc/dh895xcc_qa_dev0.conf** have replaced the ssl section with following:

> 
#############################################
\# User Process Instance Section
##############################################
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 0
NumProcesses = 32
LimitDevAccess = 0
\# Crypto - User space
Cy0Name = "UserCY0"
Cy0IsPolled = 1
Cy0CoreAffinity = 1

**openssl.cnf following:**

>
 [root@test-ssl ~]# cat /opt/xyz/ssl/ssl/openssl.cnf
openssl_conf = openssl_def
[openssl_def]
engines = engine_section
[engine_section]
qat = qat_section
[qat_section]
engine_id = qat
dynamic_path = /opt/xyz/ssl/lib/engines-1.1/qat.so
default_algorithms = RSA

**Comment by stevelinsell** [comment]
Hi @wenxin1234114,
You issue is being caused by the undefined SHA_Init symbol in your build.
Please see the following existing closed issue:
[undefined symbol: SHA_Init in QAT 1.6 driver](https://github.com/01org/QAT_Engine/issues/12)
Let me know if the details do not resolve your problem.

Steve.

**Comment by wenxin1234114** [comment]
@stevelinsell the QAT_Engine is not compatible with Openssl 1.1.0e ,which supported in nginx-1.10.3-async.l.0.3.0-002.tar.gz

**Comment by wenxin1234114** [comment]
@stevelinsell I have solved this issue ,openssl reinstall works fine.

**Comment by wenxin1234114** [comment]
I have solved this issue ,openssl reinstall works fine.
