### ISSUE TITLE
Can't init QAT engine

### ISSUE THREAD

**Issue by cmchou** [01org/QAT_Engine#35]
I have questions on using QAT with openSSL on Atom C3708.

I was using 
openSSL 1.1.0g
QAT1.7.Upstream.L.1.0.3_42
QAT Engine master build clone on Oct 5, probably 0.5.29

Here are the outputs:

ubuntu@atom-crb1:~/openssl-build/bin$ ./openssl speed -engine qat -elapsed -async_jobs 72 rsa2048
ADF_UIO_PROXY err: icp_adf_userProcessToStart: Cannot open /dev/qat_dev_processes file
[error] icp_sal_userStart() - : icp_adf_userProcessToStart failed

can't use that engine
139720415069952:error:8007D09C:lib(128):qat_engine_init:icp sal userstart fail:e_qat.c:290:
139720415069952:error:260B806D:engine routines:engine_table_register:init failed:crypto/engine/eng_table.c:125:
You have chosen to measure elapsed time instead of user CPU time.
Doing 2048 bit private rsa's for 10s: 2846 2048 bit private RSA's in 10.00s
Doing 2048 bit public rsa's for 10s: 98050 2048 bit public RSA's in 10.00s
OpenSSL 1.1.0g-dev  xx XXX xxxx
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/ubuntu/openssl-build/ssl\"" -DENGINESDIR="\"/home/ubuntu/openssl-build/lib/engines-1.1\""  -Wa,--noexecstack
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.003514s 0.000102s    284.6   9805.0

**Comment by stevelinsell** [comment]
Hi @cmchou,

Can you confirm the following:

1) Are you running as a root user? 
If not you need to follow the instructions in the Intel® QuickAssist Technology Software for Linux* - Programmer's Guide - HW version 1.7 -
Section 3.14 - Running Applications as Non-Root User.
Here is a direct link to the document, but this may go out of date over time:
https://01.org/sites/default/files/downloads/intelr-quickassist-technology/336210qatswprogguiderev001review.pdf

2) Have you followed the troubleshooting section of the engines README.md - https://github.com/01org/QAT_Engine/blob/master/README.md#troubleshooting

If you are still having problems with the openssl speed application initializing the QAT engine after trying the above then let me know and we can explore in more detail.

Kind Regards,

Steve.

**Comment by cmchou** [comment]
hi @stevelinsell,

Thanks for your super fast response. Here are my answers to your questions.

1. Not root user but config the system as the programmer's guild you mentioned.
2. Yes I went through the trouble shooting.

Here is the new message I got from running openssl with qat engine. It seems went through the non-root user guidelines eliminate some errors. 

ubuntu@atom-crb1:~/openssl-build/bin$ ./openssl speed -engine qat -async_jobs 72 rsa2048
can't use that engine
139659505174272:error:8007D09F:lib(128):qat_engine_init:instance unavailable:e_qat.c:306:
139659505174272:error:260B806D:engine routines:engine_table_register:init failed:crypto/engine/eng_table.c:125:
Doing 2048 bit private rsa's for 10s: 2846 2048 bit private RSA's in 10.00s
Doing 2048 bit public rsa's for 10s: 97907 2048 bit public RSA's in 10.00s
OpenSSL 1.1.0g-dev  xx XXX xxxx
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/ubuntu/openssl-build/ssl\"" -DENGINESDIR="\"/home/ubuntu/openssl-build/lib/engines-1.1\""  -Wa,--noexecstack
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.003514s 0.000102s    284.6   9790.7

I also notice that when showing the qat engine info. The output said "unavailable". Does it have impact to use the qat engine with openssl?

ubuntu@atom-crb1:~/openssl-build/bin$ ./openssl engine -t -c -vvvv qat
(qat) Reference implementation of QAT crypto engine
 [RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF]
     [ unavailable ]
     ENABLE_EXTERNAL_POLLING: Enables the external polling interface to the engine.
          (input flags): NO_INPUT
     POLL: Polls the engine for any completed requests
          (input flags): NO_INPUT
     SET_INSTANCE_FOR_THREAD: Set instance to be used by this thread
          (input flags): NUMERIC
     GET_NUM_OP_RETRIES: Get number of retries
          (input flags): NO_INPUT
     SET_MAX_RETRY_COUNT: Set maximum retry count
          (input flags): NUMERIC
     SET_INTERNAL_POLL_INTERVAL: Set internal polling interval
          (input flags): NUMERIC
     GET_EXTERNAL_POLLING_FD: Returns non blocking fd for crypto engine
          (input flags): NO_INPUT
     ENABLE_EVENT_DRIVEN_POLLING_MODE: Set event driven polling mode
          (input flags): NO_INPUT
     GET_NUM_CRYPTO_INSTANCES: Get the number of crypto instances
          (input flags): NO_INPUT
     DISABLE_EVENT_DRIVEN_POLLING_MODE: Unset event driven polling mode
          (input flags): NO_INPUT
     SET_EPOLL_TIMEOUT: Set epoll_wait timeout
          (input flags): NUMERIC
     SET_CRYPTO_SMALL_PACKET_OFFLOAD_THRESHOLD: Set QAT small packet threshold
          (input flags): STRING
     ENABLE_INLINE_POLLING: Enables the inline polling mode.
          (input flags): NO_INPUT

**Comment by stevelinsell** [comment]
Hi @cmchou can you confirm whether the sample code supplied with the QAT Driver runs correctly (with the original driver config files, rather than the QAT Engine ones)? 
Also when you see the errors above do you see anything in the dmesg log?

The messages you are getting above are stating that there are no Crypto instances available from the QAT Driver. The reasons this could happen are generally:

1) The QAT Driver is not installed or not up in a running state.
2) The USDM memory driver has not been insmoded so the QAT Driver is not able to allocate Pinned Contiguous memory, so it does not come up correctly.
3) The QAT Driver config files are not the ones supplied with the QAT Engine but the default ones that come with the QAT Driver, i.e. it has an [SSL] section rather than a [SHIM] section.
4) The QAT Driver config files are not configured correctly in terms of Crypto instances or NumProcesses, or are corrupt in some way.
5) There is a permissions problem perhaps with running as a non root user preventing something being accessed or preventing large memory allocations.
6) The QAT Engine has not been configured with the --enable-upstream_driver option even though running against the QAT1.7.Upstream.L.1.0.3_42 driver.

There maybe other reasons why no crypto instances are available but those are all I can think of just now. The dmesg output may help narrow which of the above is causing the issue.

Kind Regards,

Steve.

**Comment by cmchou** [comment]
Hi @stevelinsell,

I checked the list you provided. My system should have no problem with 1, 2, 3, 5, 6. I'm not sure about point 4. However I decided to switch to centOS for avoiding the permission issue. Will let you know if same issue exists after running it on centOS.

Thank you so much for your response,
Jamie

**Comment by cmchou** [comment]
Hi @stevelinsell,

I installed a brand new centOS on my system. This time QAT with openSSL works very well. Thanks for your great help.

Best regards,
Jamie
