### ISSUE TITLE
QAT+Nginx failed to handle TLS request with ECDSA cert but succes with RSA cert

### ISSUE THREAD

**Issue by cheng0201** [01org/QAT_Engine#37]
Hi all,
    I'm try to use Intel QAT card to accelerate TLS traffic in docker, it could handle TLS request with RSA cert, but failed to handle TLS request with ECDSA cert. and related test bed as below:
    OS: CentOS 7.2.1511 kernel 3.10.0-327.28.3.el7.x86_64
    QAT card: DH895x Stepping A0
    Driver: QAT1.6.L.2.6.0-65.tar.gz
    Openssl: 1.1.0f
    QAT Engine: QAT_Engine-0.5.29 compiled with <--enable-qat_debug --enable-qat_warnings --enable-qat_mem_debug --enable-qat_mem_warnings --with-qat_debug_file=/var/log/qat_engine.log --with-cc_opt="-DQAT_TESTS_LOG">
    Nginx: 1.12.0 with ported Intel pacth nginx-1.10.3-async.l.0.3.0-002
    Test Client: ab in httpd-tools-2.4.28-3
    nginx ssl config is as below:
        listen 192.168.1.26:443 ssl reuseport fastopen=1024 deferred;
        server_name 192.168.1.26 "";
        ssl_certificate /etc/nginx/certs/server_cert_ecdsa.crt;
        ssl_certificate_key /etc/nginx/certs/server_cert_ecdsa.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ALL;
        ssl_prefer_server_ciphers on;
        ssl_asynch on;
    here I deploy it as load balance:
    client(ab+openssl) --->LB(nginx+openssl+QAT Engine) ---> server
    when test with ab, ab will stuck and timeout, as it did not receive server_hello response. the ab output is as below:
         Benchmarking 192.168.1.26 (be patient)...apr_pollset_poll: The timeout specified has expired (70007)
   comparing the RSA cert case, it seem qat engine call back not trigger nginx epoll event, so at last timeout. I not sure it's Nginx issue or QAT Engine, and am taking time to dig it. please remove “.log” from file name for the first and last attached file.
       Did anybody see similar issue? Any help is appreciated.
[dh895xcc_qa_dev0.conf.txt](https://github.com/01org/QAT_Engine/files/1404831/dh895xcc_qa_dev0.conf.txt)
[qat_crypto_ecdsa.log](https://github.com/01org/QAT_Engine/files/1404833/qat_crypto_ecdsa.log)
[qat_engine_ecdsa.log](https://github.com/01org/QAT_Engine/files/1404837/qat_engine_ecdsa.log)
[nginx_error_ecdsa.log](https://github.com/01org/QAT_Engine/files/1404838/nginx_error_ecdsa.log)
[tls_ecdsa.pcap.log](https://github.com/01org/QAT_Engine/files/1404839/tls_ecdsa.pcap.log)

**Comment by stevelinsell** [comment]
Hi @cheng0201,

A few questions:

What cipher are you expecting to negotiate on your connection? I'm presuming its an ECDHE-ECDSA cipher, I'm presuming either with a form of AES-CBC or AES-GCM payload encryption?

I see no evidence of ECDH being offloaded in the trace you provided so are you configuring the QAT Engine build or OpenSSL config file to only use the QAT Engine for ECDSA? If so can you let me know whether you are doing that via the engine configure or the OpenSSL conf as it is important to know this to be able to investigate this further. It also maybe worth trying it when configured to offload everything as well in case there is something particular about the configuration you are trying to run that is causing your issue.

From your pcap trace showing the client hello it looks like that by default you will probably try and negotiate an X25519 curve for the ECDH(E) part and a P256 curve for the ECDSA part. Can you confirm which curve your EC certificate is signed with and which hashing algorithm?

Kind Regards,

Steve.

**Comment by cheng0201** [comment]
Hi Steve,
    sorry for repond later, I was trying to check whether it happen on normal host, and it prove it have the same issue on the normal host. it's for general use, so we need to support RSA, ECDHE+RSA, ECDHE+ECDSA, of course, we also need AES-CBC or AES-GCM payload encryption.
    I configure QAT engine for all the ssl traffic, indeed it could offload RSA traffic into QAT engine, one way is to keep openssl config default, and nginx config set ssl_engine as qat, another way is not to ssl_engine as qat in nginx config, but change openssl.cnf as below:
qat = qat_section
[qat_section]
engine_id = qat
dynamic_path = /opt/openssl/lib/engines-1.1/qat.so
default_algorithms = ALL
if there is way to do it through QAT Engine config, please let me know.
the attached is the used self signed ecdsa cert.
[cert.crt.txt](https://github.com/01org/QAT_Engine/files/1421550/cert.crt.txt)
[cert.key.txt](https://github.com/01org/QAT_Engine/files/1421551/cert.key.txt)

**Comment by paulturx** [comment]
Hi @cheng0201
To answer your question regarding using the QAT engine configure, the QAT engine README.md file gives details of the options available when running the QAT engine './configure' command.   One of Steve's previous questions was 👎 

_"I see no evidence of ECDH being offloaded in the trace you provided so are you configuring the QAT Engine build or OpenSSL config file to only use the QAT Engine for ECDSA? If so can you let me know whether you are doing that via the engine configure or the OpenSSL conf as it is important to know this to be able to investigate this further?"_ 

 If one wanted to disable ECDH offload to the QAT engine (and force ECDH to software) by using the QAT engine configure, the README.md gives the './configure' command option to use is:-

**--disable-qat_ecdh**

Does this answer your query?  

Regards,
    Paul Turner

**Comment by cheng0201** [comment]
Hi @paulturx ,

      thanks for your explanation, I do follow the instruction of QAT engine issue, but issue still is here. Fortunately as lat I get which result this issues and have workaround to avoid them, but it need more time to dig them.
      just summary here, so other guys could save time to check it.
      1. qaeMemDrv.ko generated after compile qatmux.l.2.6.0-60.tgz(QAT driver) is not installed after install QAT driver, because it's generated through compile sample codes, so please do not only install QAT driver and remember to run module by manually.
      2. QAT driver do not disable kernel existed driver, of course it rmmod intel_qat.ko and qat_dh895xcc.ko when install QAT driver, but kernel existed driver auto load after reload, of course QAT driver will not load. Here I just talk about QAT driver 1.6.
      3. systemctl start nginx will failed when Nginx integrate Intel patch. it take me trouble for a long time,    Intel support think I have some incorrect step when install driver, engine, indeed, he started nginx with "nginx", I start nginx with "systemctl start nginx". I think it maybe have the same reason with nginx reload issue, a known issue for Intel, as systemctl will run ExecStartPre script before run the ExecStart script.
      4. when Nginx integrate Intel patch and http server listen directive configure deferred parameter, Nginx failed to handle TLS request using ECDHE key exchange. it's OK after delete deferred parameter.
      5. when Nginx integrate Intel patch, Nginx 1.10.3 failed to handle TLS request when using ECDSA certs generated with secp384r1 and secp521r1, but it's OK for nging 1.12.0. I'm not sure it's Nginx issue or QAT issue.
      whatever, it could use now.

**Comment by cheng0201** [comment]
Hi @paulturx ,
thanks for your explanation, I do follow the instruction of QAT engine issue, but issue still is here. Fortunately as lat I get which result this issues and have workaround to avoid them, but it need more time to dig them.
  just summary here, so other guys could save time to check it.
  1. qaeMemDrv.ko generated after compile qatmux.l.2.6.0-60.tgz(QAT driver) is not installed after install QAT driver, because it's generated through compile sample codes, so please do not only install QAT driver and remember to run module by manually.
  2. QAT driver do not disable kernel existed driver, of course it rmmod intel_qat.ko and qat_dh895xcc.ko when install QAT driver, but kernel existed driver auto load after reload, of course QAT driver will not load. Here I just talk about QAT driver 1.6.
  3. systemctl start nginx will failed when Nginx integrate Intel patch. it take me trouble for a long time,    Intel support think I have some incorrect step when install driver, engine, indeed, he started nginx with "nginx", I start nginx with "systemctl start nginx". I think it maybe have the same reason with nginx reload issue, a known issue for Intel, as systemctl will run ExecStartPre script before run the ExecStart script.
  4. when Nginx integrate Intel patch and http server listen directive configure deferred parameter, Nginx failed to handle TLS request using ECDHE key exchange. it's OK after delete deferred parameter.
  5. when Nginx integrate Intel patch, Nginx 1.10.3 failed to handle TLS request when using ECDSA certs generated with secp384r1 and secp521r1, but it's OK for nging 1.12.0. I'm not sure it's Nginx issue or QAT issue.
  whatever, it could use now.
