### ISSUE TITLE
QAT_Engine for older OpenSSL version 

### ISSUE THREAD

**Issue by DucTM31** [01org/QAT_Engine#38]
Hi,

My server has the DH89xx QAT module, and I am trying to use them to offload the crypto operations for SSL/ TLS.
Currently, it's not possible for me to update to OpenSSL 1.1.0 (the server is using 1.0.1 atm).
As you stated at this thread "https://github.com/01org/QAT_Engine/issues/30", there is a qat engine for openssl 1.0.1, right? 
If so, could you please give me a link to it? I have tried to look for it on google for a while but no luck.
Another things, do you have any plan to add the support for aes-gcm at the near future?

Thank you in advance!

**Comment by paulturx** [comment]
Hi DucTM31
At present we are planning to add support for TLS1.3, after which we may  re-visit adding support for AES-GCM, but at the time of writing I cannot confirm this.

I have managed to find a link in 01.org  to a version of the QAT engine driver which will work with OpenSSL-1.0.1m: https://01.org/sites/default/files/page/libcrypto_shim_0.4.9-009_withdocumentation_0.zip.  The README file in the zip gives instructions re. installation, but any questions please let me know.

Regards,
    Paul Turner

**Comment by DucTM31** [comment]
Thank Paul,
This will save me a lot of time.
