### ISSUE TITLE
How to build QAT engine statically with OpenSSL

### ISSUE THREAD

**Issue by InfoHunter** [01org/QAT_Engine#9]
hi guys,

I am wondering how to build qat engine statically, since the documents provided by Intel all mention the way how to build the engine into qat.so and how to link it to OpenSSL dynamically. So is there a way to build an ".a" library or build qat engine into libcrypto.a so that I can link qat statically along with OpenSSL into my application. That would be very helpful in my scenario.

Hoping for responding asap, thanks!

**Comment by agrandi** [comment]
Hi @InfoHunter 

With OpenSSL 1.1.0, all the 3rd party engines are loaded dynamically at run time.
Compiling the engine statically would require to make significant changes to the Makefiles of OpenSSL.

Our goal is to provide an engine that works with a *vanilla* version of OpenSSL and for this reason we don't plan to add support for static compilation.


Another thing to keep in mind is that our build scripts are now based on **autotools**.
Instead, OpenSSL uses a custom build system that has been written from scratch.
Integrating the two compilation scripts is not straightforward and we cannot provide support.

Out of curiosity, what problem are you trying to solve by moving to a static build?

**Comment by InfoHunter** [comment]
Okay, that's understood. The problem at my side is not big, our existing packaging system only supports to pack static build applications (that means to pack one binary with all depending libs built into it), but it's not a big deal for us to move to a dynamic build and pack extra '.so' files(that means we need to adjust our RPM packaging spec file). So I was seeking for a 'static' solution just before we start to modify the packaging system. So it's fine for me to use a dynamic build, thanks anyway for the information.
